name: Deploy to Main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    if: contains('tharaka911 virajjayarathna', github.actor)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          echo "Deploying application..."
